name: store
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  build_runner: ^2.4.15
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.6.8
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  firebase_auth: ^5.5.4
  firebase_core: ^3.13.1
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localization: ^0.3.2
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_staggered_grid_view: ^0.7.0
  flutter_svg: ^2.1.0
  geocoding: ^4.0.0
  geolocator: ^14.0.1
  go_router: ^15.1.1
  google_maps_drawing_tools: ^0.0.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  image_picker: ^1.1.2
  intl: ^0.20.2
  path_provider: ^2.1.5
  shimmer: ^3.0.0
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/
flutter_intl:
  enabled: true
