// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPTV7iLEqxqYMFoD_CJr9GXMZIneBcqDg',
    appId: '1:22173469061:web:008f4cdd5313533c38dcec',
    messagingSenderId: '22173469061',
    projectId: 'freshly-374aa',
    authDomain: 'freshly-374aa.firebaseapp.com',
    storageBucket: 'freshly-374aa.firebasestorage.app',
    measurementId: 'G-SDY6VVQQ9T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp88lSDftcHnAMC8sWaN4amgi7uEP3MD0',
    appId: '1:22173469061:android:82e77654a484393438dcec',
    messagingSenderId: '22173469061',
    projectId: 'freshly-374aa',
    storageBucket: 'freshly-374aa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLxqEYyvOYjXwf2_BN2U6iVSFUKDZvFOM',
    appId: '1:22173469061:ios:979d40abc8c5ba3a38dcec',
    messagingSenderId: '22173469061',
    projectId: 'freshly-374aa',
    storageBucket: 'freshly-374aa.firebasestorage.app',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLxqEYyvOYjXwf2_BN2U6iVSFUKDZvFOM',
    appId: '1:22173469061:ios:979d40abc8c5ba3a38dcec',
    messagingSenderId: '22173469061',
    projectId: 'freshly-374aa',
    storageBucket: 'freshly-374aa.firebasestorage.app',
    iosBundleId: 'com.example.store',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCPTV7iLEqxqYMFoD_CJr9GXMZIneBcqDg',
    appId: '1:22173469061:web:043b80a626ed470838dcec',
    messagingSenderId: '22173469061',
    projectId: 'freshly-374aa',
    authDomain: 'freshly-374aa.firebaseapp.com',
    storageBucket: 'freshly-374aa.firebasestorage.app',
    measurementId: 'G-JXPWWQP4RJ',
  );
}
